# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos: # hvor hooks kommer fra
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0 # fast version (reproducerbarhed!)
    hooks: # konkrete checks der k√∏res ved git commit
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: check-added-large-files
